### ISSUE TITLE
Adding a functionality

### ISSUE THREAD

**Issue by codemaniac-sahil** [goodchai0/day-planner#13]
Add a functionality when the user presses enter the result should be saved.

**Comment by Swathi-L** [comment]
Hi @codemaniac-sahil, @goodchai0, can I work on this?

**Comment by goodchai0** [comment]
please star the repo

**Comment by codemaniac-sahil** [comment]
@goodchai0 I resolved the issue please check my PR https://github.com/goodchai0/day-planner/pull/93
