### ISSUE TITLE
Delete Task not functioning correctly when multiple task are present for an hour

### ISSUE THREAD

**Issue by darshanshah1996** [goodchai0/day-planner#31]
Hi @goodchai0 

Currently when there are `multiple task` present for an `hour` clicking on any task always the `last task` gets deleted

Can you assign me the issue

Screencast for the issue

https://www.loom.com/share/4d4af09a7e494484a35aad05b1f78886

**Comment by goodchai0** [comment]
Go for it

**Comment by goodchai0** [comment]
star the repo too

**Comment by darshanshah1996** [comment]
Closing the issue as related pr https://github.com/goodchai0/day-planner/pull/58 is merged
