### ISSUE TITLE
Add scroll to top button feature

### ISSUE THREAD

**Issue by anupeshverma** [goodchai0/day-planner#54]

**Comment by anupeshverma** [comment]
I want to add scroll to top feature please assign me this task
@goodchai0

**Comment by harika1314** [comment]
i wanted to contribute to this,can you assign this task to me
@goodchai0 .

**Comment by sabhisharma-ise** [comment]
Please assignt this issue to me!

**Comment by KeneePatel** [comment]
Can this issue be considered close as required pull request has been merged.

**Comment by anupeshverma** [comment]
yes thanks
