### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by Saran-pariyar** [goodchai0/day-planner#67]
I tried to use dark mode, there are 2 buttons to switch to dark mode but none of them is working or making any changes.
![Screenshot from 2022-10-15 15-40-53](https://user-images.githubusercontent.com/86418083/195980326-027ea311-c254-4323-b183-d8900f7f8d25.png)

**Comment by goodchai0** [comment]
Go for it, and please star the repo too.

**Comment by DevDK12** [comment]
I would Like to work on it

**Comment by Saran-pariyar** [comment]
> I would Like to work on it

Please admin assign this issue to him, I was just raising the issue.
You can go for it buddy

**Comment by DevDK12** [comment]
Yeah I am near solution , please assign this to me @goodchai0

**Comment by DevDK12** [comment]
@Saran-pariyar or admin @goodchai0  you can close this issue.
