### ISSUE TITLE
Add a readme . So, that people can understand about the project

### ISSUE THREAD

**Issue by wizeewig** [goodchai0/day-planner#8]
@goodchai0 May I?

**Comment by goodchai0** [comment]
Go ahead!! Don't forget to star the repo.

**Comment by ash-u-170602** [comment]
@goodchai0 I can do this

**Comment by goodchai0** [comment]
Already assigned to someone else. You can find some other issue in this repo and contribute.

**Comment by goodchai0** [comment]
> @goodchai0 I can do this
> 

Already assigned to someone else. You can find some other issue in this repo and contribute.
