### ISSUE TITLE
Redesign the footer

### ISSUE THREAD

**Issue by zugzwang03** [goodchai0/day-planner#89]
![footer](https://user-images.githubusercontent.com/95460021/196089094-9c031ac2-f19d-4dfb-9170-44d1a5fdb04f.png)

The footer contains some dummy text with unclickable links of social media handles.  I want to remove these bugs. Can I make this contribution under Hacktoberfest'22?

**Comment by Nikita0509** [comment]
i would like to contribute plz assign me this project under hacktoberfest 2022

**Comment by ShrutiKoli19** [comment]
If this has not been solved yet, can you assign it to me

**Comment by gitamandeep** [comment]
@goodchai0 please assign this issue to me i can fix it
